apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarazor-deployment
  labels:
    app: binarazor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarazor
  template:
    metadata:
      labels:
        app: binarazor
    spec:
      containers:
        - name: binarazor
          image: sagar87/binarazor:marc
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "1000m"
              memory: "16Gi"
            limits:
              cpu: "2000m"
              memory: "32Gi"
          env:
            - name: ENV
              value: "production"
            - name: PROJECT
              valueFrom:
                secretKeyRef:
                  name: binarazor-credentials
                  key: PROJECT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: binarazor-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: binarazor-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_URL
              valueFrom:
                secretKeyRef:
                  name: binarazor-credentials
                  key: AWS_URL
            - name: AWS_PATH
              valueFrom:
                secretKeyRef:
                  name: binarazor-credentials
                  key: AWS_PATH
            - name: MONGO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-port
            - name: MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: binarazor-service
spec:
  type: LoadBalancer
  selector:
    app: binarazor
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
