apiVersion: v1
kind: Service
metadata:
  name: binarazor-service
spec:
  type: LoadBalancer
  selector:
    app: binarazor
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: binarazor-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: sectigo
spec:
  ingressClassName: internal-users
  rules:
    - host: binarazor.embl.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: binarazor-service
                port:
                  number: 8501
